version: "3"
services:
  cbamp-notification:
    image: slack-notification:${TAG}
    environment:
      SLACK_TOKEN: ${BUILDKITE_PLUGIN_NIGHTWATCH_SLACK_NOTIFICATION_SLACK_TOKEN}
      SLACK_CHANNEL: ${BUILDKITE_PLUGIN_NIGHTWATCH_SLACK_NOTIFICATION_SLACK_CHANNEL}
      BUILDKITE_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
      BUILDKITE_BUILD_URL: ${BUILDKITE_BUILD_URL}
      BUILDKITE_PIPELINE_NAME: ${BUILDKITE_PIPELINE_NAME}
      BUILDKITE_BRANCH: ${BUILDKITE_BRANCH}
      BUILDKITE_MESSAGE: ${BUILDKITE_MESSAGE}
      BUILDKITE_COMMIT: ${BUILDKITE_COMMIT}
      BUILDKITE_BUILD_AUTHOR: ${BUILDKITE_BUILD_AUTHOR}
    command: node /app/dist/index.js