name: Junit-slack-notification
description: Notify Slack with a summary of the Junit build
author: https://github.com/franklychilled
main: index.js
version: 1.0
requirements:
  - docker
configuration:
  properties:
    artifacts:
      type: string
    SLACK_TOKEN:
      type: string
    SLACK_CHANNEL:
      type: string
    DOCKER_CACHE:
      type: string
  required:
    - artifacts
    - SLACK_TOKEN
    - SLACK_CHANNEL
  additionalProperties: false