name: Nightwatch slack notification
description: Notify Slack with a summary of the Nightwatch build
author: https://github.com/franklychilled
requirements:
  - docker
configuration:
  properties:
    artifacts:
      type: string
    SLACK_TOKEN:
      type: string
    SLACK_CHANNEL:
      type: string
  required:
    - artifacts
#    - SLACK_TOKEN
#    - SLACK_CHANNEL
  additionalProperties: false