name: "Create AWS Secret for Slack API token"
steps:
  - block: "Capture details"
    fields:
      - text: "Slack API Access token"
        key: "secret_value"
        hint: "Nightwatch Summary Slack API Access token secret to store"
        required: true
      - text: "AWS cli"
        key: "aws-cli"
        hint: "The aws-cli image to use (like: amazon/aws-cli:2.0.30)"
        required: true
      - text: "Queue"
        key: "buildkite-queue"
        hint: "The name of the queue in buildkite (like: default.linux)"
        required: true
  - label: "Generate secrets pipeline for account"
    command: .buildkite/scripts/secret-creator.sh
    timeout_in_minutes: 10
