version: '3.2'

services:
  aws_cli:
    image: ${AWS_CLI}
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - AWS_REGION
      - AWS_SESSION_TOKEN
      - AWS_SECRET_ACCESS_KEY
    working_dir: /app
    volumes:
      - .:/app:rw
      - ~/.aws:/root/.aws
